input_all_players_public_hash = ""
input_game_ended = ""
input_game_state_hash = ""
input_turn_count = ""
input_user_state_hash = ""
my_player_index = ""
p0_game_player_index = ""
p0_player_id = ""
p0_role = ""
p0_section_id = ""
p0_status = ""
p1_game_player_index = ""
p1_player_id = ""
p1_role = ""
p1_section_id = ""
p1_status = ""
p2_game_player_index = ""
p2_player_id = ""
p2_role = ""
p2_section_id = ""
p2_status = ""
p3_game_player_index = ""
p3_player_id = ""
p3_role = ""
p3_section_id = ""
p3_status = ""
p4_game_player_index = ""
p4_player_id = ""
p4_role = ""
p4_section_id = ""
p4_status = ""
p5_game_player_index = ""
p5_player_id = ""
p5_role = ""
p5_section_id = ""
p5_status = ""
p6_game_player_index = ""
p6_player_id = ""
p6_role = ""
p6_section_id = ""
p6_status = ""
private_encrypt_secret = ""
private_mask_secret = ""
private_voted_for_index = ""
target_section = ""
visible_sections = ["", "", "", "", "", "", "", "", ""]
